galaxy_info:
  author: Mats Blomdahl
  description: Add monitoring for server logs
  company: National Library of Sweden

  license: Apache-2.0

  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - docker
    - logging

dependencies:
  - docker
